explanation = {'Age': 'Numerical Value',
'Attrition': 'Employee leaving the company (0=no, 1=yes)',
'BusinessTravel': '(1=No Travel, 2=Travel Frequently, 3=Travel Rarely)',
'DailyRate': 'Numerical Value - Salary Level',
'Department': '(1=HR, 2=R&D, 3=Sales)',
'DistanceFromHome': 'Numerical Value - THE DISTANCE FROM WORK TO HOME',
'Education': "Numerical Value. (1 'Below College' 2 'College' 3 'Bachelor' 4 'Master' 5 'Doctor')",
'EducationField': '(1=HR, 2=LIFE SCIENCES, 3=MARKETING, 4=MEDICAL SCIENCES, 5=OTHERS, 6= TECHNICAL)',
'EmployeeCount': 'Numerical Value',
'EmployeeNumber': 'Numerical Value - EMPLOYEE ID',
'EnvironmentSatisfication': "Numerical Value - SATISFACTION WITH THE ENVIRONMENT (1 'Low' 2 'Medium' 3 'High' 4 'Very High')",
'Gender': '(1=FEMALE, 2=MALE)',
'HourlyRate': 'Numerical Value - HOURLY SALARY',
'JobInvolvement': "Numerical Value - JOB INVOLVEMENT (1 'Low' 2 'Medium' 3 'High' 4 'Very High')",
'JobLevel': 'Numerical Value - LEVEL OF JOB',
'JobRole': "(1=HR REP, 2=HR, 3=LAB TECHNICIAN, 4=MANAGER, 5= MNG DIRECTOR, 6= RESEARCH DIRECTOR,",
' ': '7= RESEARCH SCIENTIST, 8=SALES EXECUTIVE, 9= SALES REPRESENTATIVE)',
'JobSatisfication': "Numerical Value - SATISFACTION WITH THE JOB (1 'Low' 2 'Medium' 3 'High' 4 'Very High')",
'MaritalStatus': "(1=DIVORCED, 2=MARRIED, 3=SINGLE)",
'MonthlyIncome': 'Numerical Value - MONTHLY SALARY',
'MonthlyRate': 'Numerical Value - MONTHLY RATE',
'NumCompaniesWorked': 'Numerical Value - NO. OF COMPANIES WORKED AT',
"Over18": '(1=YES, 2=NO)',
'OverTime': '(1=NO, 2=YES)',
'PercentSalaryHike': 'Numerical Value - PERCENTAGE INCREASE IN SALARY',
'PerformanceRating': "Numerical Value - PERFORMANCE RATING",
'RelationshipSatisfication': 'Numerical Value - RELATIONS SATISFACTION',
'StandardHours': 'Numerical Value - STANDARD HOURS',
'StockOptionLevel': 'Numerical Value - STOCK OPTIONS (Higher the number, the more stock option an employee has)',
'TotalWorkingYears': 'Numerical Value - TOTAL YEARS WORKED',
'TrainingTimesLastYear': 'Numerical Value - HOURS SPENT TRAINING',
'WorkLifeBalance': 'Numerical Value - TIME SPENT BETWEEN WORK AND OUTSIDE',
'YearsAtCompany': 'Numerical Value - TOTAL NUMBER OF YEARS AT THE COMPANY',
'YearsInCurrentRole': 'Numerical Value -YEARS IN CURRENT ROLE',
'YearsSinceLastPromotion': 'Numerical Value - LAST PROMOTION',
'YearsWithCurrManager': 'Numerical Value - YEARS SPENT WITH CURRENT MANAGER'}